Copy libselinux-python into virtualenv if required
I think it might be better to just create the virtualenv with
--system-site-packages so that the system's libselinux-python bindings
are picked up automatically, but I haven't verified that this fixes the
problem (whatever it is).

If we use --system-site-packages, we might be able to cut down on our
dependency list to some extent (for the non-critical modules).

diff --git a/bin/tpaexec b/bin/tpaexec
--- a/bin/tpaexec
+++ b/bin/tpaexec
@@ -70,6 +70,7 @@ _create_and_activate_virtualenv() {
     # activate it below.
 
     if [[ ! -d $vpath ]]; then
+        echo "Creating virtualenv $vpath"
         if ! command -v virtualenv &>/dev/null; then
             error "can't find virtualenv in PATH (please install python-virtualenv)"
         fi
@@ -77,6 +78,20 @@ _create_and_activate_virtualenv() {
             error "couldn't create $vpath (try ``--virtualenv /other/path`` or use sudo)"
         fi
         virtualenv $vpath
+    fi
+
+    # For RedHat-derivatives, we need to work around a known virtualenv
+    # bug related to libselinux-python
+
+    if [[ -f /etc/redhat-release ]]; then
+        if [[ ! -d $vpath/lib/python2.7/site-packages/selinux ]]; then
+            echo "Copying /usr/lib64/python2.7/site-packages/selinux to virtualenv"
+            cp -rp /usr/lib64/python2.7/site-packages/selinux \
+                $vpath/lib/python2.7/site-packages
+            if [[ $? -ne 0 ]]; then
+                error "couldn't copy libselinux-python to virtualenv"
+            fi
+        fi
     fi
 
     _activate_virtualenv $vpath
