Report source location when bin/tpaexec hits an error
Set up an error trap and ensure it propagates into functions
and through pipelines.

Allows tpaexec commands to exit with a more informative
error like:

    ERROR: unexpected error 1 at bin/tpaexec:157 in function _apply_patches

instead of a silent exit or just the error from the failing
command itself.

diff --git a/bin/tpaexec b/bin/tpaexec
--- a/bin/tpaexec
+++ b/bin/tpaexec
@@ -6,12 +6,28 @@
 
 IFS=$' \t\n'
 set -eu
+# Pass exit code through pipelines
+set -o pipefail
+# Fire ERR trap inside functions
+set -E
+# Set pager if unset
 : "${PAGER:=less}"
 
 error() {
+    trap ERR
     echo "ERROR: $*" >&2
     exit 1
 }
+
+function unexpected_error_handler() {
+   if [ -n "${errfunc}" ]; then
+      error "unexpected error ${errcode} at ${errfile}:${errline} in function ${errfunc}"
+   else
+      error "unexpected error ${errcode} at ${errfile}:${errline}"
+   fi
+}
+
+trap 'errcode=$?; errline=$LINENO; errfile=$0; errfunc=${FUNCNAME:-}; unexpected_error_handler' ERR
 
 # If $TPA_DIR is not already set, we guess TPA_DIR based on $0 (so that
 # a git checkout takes precedence over a package installation), or use
