Move distribution→AMI translation to architectures/lib/image
Again, this is something Training/configure knew how to do, and which
other architectures need to use. They can now do so with something like:

    image=$($libdir/image $distribution $platform)
    eval $image

(Also make sure all errors go to stderr, because the above calling
convention does rather depend on it.)

diff --git a/architectures/Training/configure b/architectures/Training/configure
--- a/architectures/Training/configure
+++ b/architectures/Training/configure
@@ -47,14 +47,14 @@ while [[ $# -gt 0 ]]; do
             shift
             ;;
         *)
-            echo "ERROR: unrecognised parameter: $opt"
+            echo "ERROR: unrecognised parameter: $opt" >&2
             exit 1
             ;;
     esac
 done
 
 if [[ ! "${issue:-}" || ! "${instances:-}" ]]; then
-    echo "ERROR: --redmine-id <num> and --instances <num> are both required"
+    echo "ERROR: --redmine-id <num> and --instances <num> are both required" >&2
     exit 1
 fi
 
@@ -65,58 +65,12 @@ distribution=${distribution:-Debian}
 minimal=${minimal:-''}
 
 if [[ "$platform" != "aws" ]]; then
-    echo "ERROR: currently unsupported platform: $platform (use '--platform aws')"
+    echo "ERROR: currently unsupported platform: $platform (use '--platform aws')" >&2
     exit 1
 fi
 
-case "$distribution$minimal" in
-    Debian)
-        ami_name=TPA-Debian-PGDG-10-2018*
-        ami_owner=self
-        ;;
-
-    Debian-minimal)
-        ami_name=debian-stretch-hvm-x86_64-gp2-2018-04-09-292
-        ami_owner=379101102735
-        ;;
-
-    RedHat)
-        ami_name=TPA-RedHat-PGDG-10-2018*
-        ami_owner=self
-        ;;
-
-    RedHat-minimal)
-        ami_name=RHEL-7.4_HVM_GA-20170808-x86_64-2-Hourly2-GP2
-        ami_owner=309956199498
-        ;;
-
-    Ubuntu)
-        ami_name=TPA-Ubuntu-PGDG-10-2018*
-        ami_owner=self
-        ;;
-
-    Ubuntu-minimal)
-        ami_name=ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20180228.1
-        ami_owner=099720109477
-        ;;
-
-    *)
-        echo "ERROR: unsupported distribution: $distribution$minimal"
-        exit 1
-        ;;
-esac
-
-case "$distribution" in
-    Debian)
-        ami_user=admin
-        ;;
-    RedHat)
-        ami_user=ec2-user
-        ;;
-    Ubuntu)
-        ami_user=ubuntu
-        ;;
-esac
+image=$($libdir/image "$distribution$minimal" $platform)
+eval $image
 
 mkdir $cluster
 
@@ -137,9 +91,9 @@ cluster_rules:
   - {proto: tcp, from_port: 0, to_port: 65535, cidr_ip: 0.0.0.0/0}
 
 ec2_ami:
-  Name: $ami_name
-  Owner: $ami_owner
-ec2_ami_user: $ami_user
+  Name: $image_name
+  Owner: $image_owner
+ec2_ami_user: $image_user
 
 ec2_vpc:
   Name: Test
diff --git a/architectures/lib/hostnames b/architectures/lib/hostnames
--- a/architectures/lib/hostnames
+++ b/architectures/lib/hostnames
@@ -20,7 +20,7 @@ pattern=${3:-'^[a-zA-Z0-9-]*$'}
 
 type realpath &>/dev/null && namesfile=$(realpath $namesfile)
 if [[ ! -f $namesfile ]]; then
-    echo "ERROR: could not open hostname list: $namesfile"
+    echo "ERROR: could not open hostname list: $namesfile" >&2
     exit 1
 fi
 
diff --git a/bin/tpaexec b/bin/tpaexec
--- a/bin/tpaexec
+++ b/bin/tpaexec
@@ -187,7 +187,7 @@ REHYDRATE
 }
 
 error() {
-    echo "ERROR: $@"
+    echo "ERROR: $@" >&2
     exit 1
 }
 
@@ -206,8 +206,7 @@ case "$exec" in
         command=$exec
         ;;
     *)
-        echo "ERROR: unrecognised tpaexec command link: $exec"
-        exit 1
+        error "unrecognised tpaexec command link: $exec"
         ;;
 esac
 
